### ISSUE TITLE
build failure at c74a863 and missing assets

### ISSUE THREAD

**Issue by stephengold** [capdevon/Archer-Game-Template2#2]
I checked out c74a8635b96086ab69c95fc10b899f2e9007544a and tried to build it in v3.2.4 of the JME SDK. However there are undefined classes:
```text
/home/sgold/Git/Archer-Game-Template2/src/main/java/mygame/Main.java:22: error: cannot find symbol
public class Main extends BaseGameApplication {
                          ^
  symbol: class BaseGameApplication
```
Perhaps a file is missing from the repo?

I substituted `SimpleApplication` for `BaseGameApplication` so the build would complete. But then I encountered a missing J3MD asset:
```text
Mar 14, 2021 3:42:20 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetNotFoundException: MatDefs/Materialize/MaterializePBR.j3md
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:371)
	at com.jme3.material.Material.<init>(Material.java:104)
	at mygame.CubeAppState.getMaterializePBR(CubeAppState.java:103)
	at mygame.CubeAppState.createCube(CubeAppState.java:85)
	at mygame.CubeAppState.spawnObject(CubeAppState.java:60)
	at mygame.CubeAppState.update(CubeAppState.java:48)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:356)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:255)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
```

In order to run the app, I added 5 files from https://github.com/jMonkeyEngine-archive/jme-materialize-jayfella-github 
+ src/main/resources/MatDefs/Materialize/MaterializePBR.frag
+ src/main/resources/MatDefs/Materialize/MaterializePBR.j3md
+ src/main/resources/MatDefs/Materialize/MaterializePBR.vert
+ src/main/resources/Textures/grid.png
+ src/main/resources/Textures/noise-x3-512.png

**Comment by capdevon** [comment]
hi Stephen, thanks for reporting. I will check the project as soon as possible.

**Comment by capdevon** [comment]
* I have updated the build.gradle script with MavenCentral and the latest version of Minie-v.4.0.2.
* I added the ability to specify a BitMask for the physical raycast in the **Physics** class.
* I have updated the Main class which now extends SimpleApplication. 
* The 5 resource files you reported to me are in the **jme-materialize.jar** library, which is located in the **lib** folder (https://github.com/capdevon/Archer-Game-Template2/tree/main/lib). After running "Refresh Gradle Project" from eclipse, you need to manually add the library back to the "Build Path". 

Let me know if there are any further problems.

**Comment by stephengold** [comment]
I clone SHA1 id = a40f52a and encountered a new build issue, apparently caused by intrusive whitespace in "Physics.java":

```text
> Task :compileJava FAILED
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:28: error: ')' expected
    public static final Vector3f DEFAULT_GRAVITY = new Vector3f(0, -9.81 f, 0).multLocal(2);
                                                                        ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:28: error: illegal start of type
    public static final Vector3f DEFAULT_GRAVITY = new Vector3f(0, -9.81 f, 0).multLocal(2);
                                                                          ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:28: error: <identifier> expected
    public static final Vector3f DEFAULT_GRAVITY = new Vector3f(0, -9.81 f, 0).multLocal(2);
                                                                           ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:28: error: ';' expected
    public static final Vector3f DEFAULT_GRAVITY = new Vector3f(0, -9.81 f, 0).multLocal(2);
                                                                             ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:28: error: illegal start of type
    public static final Vector3f DEFAULT_GRAVITY = new Vector3f(0, -9.81 f, 0).multLocal(2);
                                                                              ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:28: error: illegal start of type
    public static final Vector3f DEFAULT_GRAVITY = new Vector3f(0, -9.81 f, 0).multLocal(2);
                                                                                         ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:63: error: ')' expected
        float height = Math.max(bb.getYExtent(), radius * 2.5 f);
                                                             ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:63: error: illegal start of expression
        float height = Math.max(bb.getYExtent(), radius * 2.5 f);
                                                               ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:64: error: ';' expected
        float mass = 50 f;
                       ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:64: error: not a statement
        float mass = 50 f;
                        ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:107: error: ')' expected
            float strength = (1. f - FastMath.clamp(distance / explosionRadius, 0, 1)) * explosionForce;
                                ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:107: error: not a statement
            float strength = (1. f - FastMath.clamp(distance / explosionRadius, 0, 1)) * explosionForce;
                                   ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:107: error: ';' expected
            float strength = (1. f - FastMath.clamp(distance / explosionRadius, 0, 1)) * explosionForce;
                                                                                     ^
/home/sgold/Git/ext/Archer-Game-Template2/src/main/java/com/capdevon/physx/Physics.java:107: error: not a statement
            float strength = (1. f - FastMath.clamp(distance / explosionRadius, 0, 1)) * explosionForce;
                                                                                         ^
```

**Comment by capdevon** [comment]
can you try again now?

**Comment by stephengold** [comment]
Now it builds fine, but immediately after I run the app I get
```text
Mar 16, 2021 3:40:09 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetNotFoundException: MatDefs/Materialize/MaterializePBR.j3md
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:371)
	at com.jme3.material.Material.<init>(Material.java:104)
	at mygame.CubeAppState.getMaterializePBR(CubeAppState.java:103)
	at mygame.CubeAppState.createCube(CubeAppState.java:85)
	at mygame.CubeAppState.spawnObject(CubeAppState.java:60)
	at mygame.CubeAppState.update(CubeAppState.java:48)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:356)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:255)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by capdevon** [comment]
you have to manually re-add the **jme-materialize.jar** library to the build path, because **gradle** removes it every time you run the upgrade script.

**Comment by stephengold** [comment]
I believe you could solve that issue by adding a couple lines to build.gradle:

```diff
+++ b/build.gradle
@@ -61,6 +61,7 @@
     maven { url 'https://dl.bintray.com/stephengold/org.jmonkeyengine' }
     maven { url 'https://jitpack.io' }
     //google()
+    flatDir { dirs file('lib') }
 
     // Read more about repositories here:
     //   https://docs.gradle.org/current/userguide/dependency_management.html#sec:repositories
@@ -85,6 +86,7 @@
 
     // Additional filters
     implementation 'com.github.polincdev:ShaderBlowEx:-SNAPSHOT'
+    runtimeOnly 'com.github.jayfella:jme-materialize:'
 
     // select one version of LWJGL (from mavenCentral or mavenLocal)
     runtimeOnly 'org.jmonkeyengine:jme3-lwjgl:' + jmonkeyengineVersion  // LWJGL 2.x
```

**Comment by capdevon** [comment]
I'm not very familiar with gradle yet. Ok, changes added.

**Comment by stephengold** [comment]
It's got a steep learning curve, especially for those of us (myself included) who don't use Groovy for anything else.
